### ISSUE TITLE
case insensitive search

### ISSUE THREAD

**Issue by regevran** [yegappan/mru#52] opened 2022-02-08 11:14 UTC
I would like to be able to search MRU files case insensitively.
From the command itself (preferred), such as - 
`:MRU -i MyFile`  - finds myfile , MYFILE, mYFiLe, etc.
Or (less preferred) by setting a variable: `g_mru_case_sensitive=1` (or 0 for insensitive).
Or in any other way.

Footnote -
MRU is the FIRST and sometimes the only extension I install in a new environment.
So - thanks a lot for it!
Recently I switched to a project that case is not important and files have names that I can't predict their case, this is the reason I want it just now after years of usage.

**Comment by yegappan** [comment] 2022-08-14 18:47
The MRU plugin already searches for file names ignoring the case. In this case, if you try completing the arguments to the ":MRU" command, you will see that all the file names matching the pattern ignoring the case are listed (myfile, MYFILE, MyFile, etc.).  Similarly if you run the ":MRU myfile" command, it will open the MRU window and list all the file names matching this pattern (ignoring the case).

**Comment by regevran** [comment] 2022-08-16 05:04
The behavior is not something I would expect, and not as simple as you described in your answer.
I am not using the tab completion, I find it inconvenient.
I prefer typing part of the name, enter, and see the list. 

Having -
```
ran@:~$ grep -i myfile .vim_mru_files
/home/ran/myfile
/home/ran/mYfIlE
/home/ran/MYFILE
/home/ran/MyFile
```

The results are as follow:
```
:MRU M
MyFile (/home/ran/MyFile)
MYFILE (/home/ran/MYFILE)
```

```:MRU My``` - MyFile is opened.
```:MRU mY``` - mYfIlE is opened.
```:MRU MY``` - MYFILE is opened.
```:MRU my``` - myfile is opened. 

But! 
During the preparation of this reply, I tried using the \C and \c vim's search modifiers and yes! it works:
```
:MRU file
myfile (/home/ran/myfile)
```

```
:MRU \cfile
MYFILE (/home/ran/MYFILE)
myfile (/home/ran/myfile)
mYfIlE (/home/ran/mYfIlE)
MyFile (/home/ran/MyFile)
```

I think that now I am happy.

**Comment by yegappan** [comment] 2022-08-17 01:41
I am not able to reproduce this problem on a Ubuntu and MS-Windows system. Which system are you using? Are you setting any of the case related options (ignorecase, smartcase, infercase, etc.) in your .vimrc file?

**Comment by regevran** [comment] 2022-08-17 07:41
Currently I am working on WSL2 on windows 10. In the past I used Ubuntu and CentOS. I am quite sure that MRU was case sensitive in all these systems.
I am using vim's `smartcase` option.

**Comment by yegappan** [comment] 2022-08-18 04:34
I was not able to reproduce the problem because I am using the latest version of Vim where fuzzy search is supported. Once I disabled the fuzzy search, I was able to reproduce the issue.  I have committed 5d5f41a984a28f8fca1eef8e49a3badf4e9f224a to address this.

**Closed** 2022-08-20 00:40 UTC

**Comment by regevran** [comment] 2022-08-24 15:55
Thanks a lot!
